[siem_core]
siem_ingest ansible_host=192.168.1.35 host_role=ingest
siem_processing ansible_host=192.168.1.37 host_role=processing
siem_storage ansible_host=192.168.1.38 host_role=storage
siem_web ansible_host=192.168.1.39 host_role=control-plane
siem_transport ansible_host=192.168.1.40 host_role=transport

[vulnerability]
vuln_mgr ansible_host=10.20.30.122 host_role=vulnerability-manager

[pilot]
pilot_web ansible_host=10.20.30.123 host_role=pilot-web
pilot_db ansible_host=10.20.30.124 host_role=pilot-db
pilot_cache ansible_host=10.20.30.125 host_role=pilot-cache

[monitored:children]
siem_core
vulnerability
pilot

[all:vars]
ansible_user=rdegon
ansible_ssh_common_args=-o StrictHostKeyChecking=no
