ALTER TABLE siem.filter_rules DELETE WHERE id IN (3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013);

INSERT INTO siem.filter_rules
(id, name, description, priority, expr, action, tags, enabled)
VALUES
(
    3001,
    'Drop Linux session success chatter',
    'Suppresses high-volume successful session lifecycle events that do not add triage value.',
    10,
    'event.category == ''session'' and event.outcome == ''success''',
    'drop',
    [],
    1
),
(
    3002,
    'Drop low-severity service lifecycle events',
    'Removes service start/stop audit noise after normalization.',
    20,
    'event.category == ''service'' and severity == ''low''',
    'drop',
    [],
    1
),
(
    3003,
    'Tag Linux audit detail records',
    'Marks PATH/CWD/PROCTITLE detail records as low-priority audit context.',
    30,
    'subcategory == ''audit_path'' or subcategory == ''audit_cwd'' or subcategory == ''audit_proctitle''',
    'tag',
    ['noise.audit_detail'],
    1
),
(
    3004,
    'Tag Linux firewall block noise',
    'Marks UFW block events as perimeter noise unless promoted by another detector.',
    40,
    'subcategory == ''linux_firewall_blocked''',
    'tag',
    ['noise.firewall'],
    1
),
(
    3005,
    'Tag SSH invalid-user probes',
    'Marks SSH invalid-user probes as internet exposure noise for easier filtering.',
    50,
    'subcategory == ''ssh_invalid_user''',
    'tag',
    ['noise.auth_probe'],
    1
),
(
    3006,
    'Drop systemd informational syslog',
    'Suppresses repetitive low-value systemd informational messages from Linux hosts.',
    60,
    'category == ''syslog'' and severity == ''info'' and process.name == ''systemd''',
    'drop',
    [],
    1
),
(
    3007,
    'Drop OpenClaw expected research activity',
    'Suppresses OpenClaw research and investigation commands that are explicitly allowlisted during normalization.',
    70,
    'tags contains ''allowlist:openclaw_research_activity''',
    'drop',
    [],
    1
),
(
    3008,
    'Drop OpenClaw expected DNS and proxy runtime noise',
    'Suppresses allowlisted OpenClaw DNS fan-out and expected proxy runtime chatter before it reaches alerting.',
    80,
    'tags contains ''allowlist:openclaw_expected_dns'' or tags contains ''allowlist:openclaw_proxy_runtime''',
    'drop',
    [],
    1
),
(
    3009,
    'Drop SIEM operational sudo checks',
    'Suppresses allowlisted SIEM health and service checks executed through privileged operator commands.',
    90,
    'tags contains ''allowlist:siem_operational_sudo''',
    'drop',
    [],
    1
),
(
    3010,
    'Drop OpenClaw expected activity markers',
    'Suppresses generic OpenClaw expected activity markers that were explicitly tagged during normalization.',
    100,
    'tags contains ''allowlist:openclaw_expected_activity''',
    'drop',
    [],
    1
),
(
    3011,
    'Drop OpenClaw audit socket noise',
    'Suppresses expected auditd socket send/connect telemetry emitted by OpenClaw itself during research and Telegram delivery activity.',
    110,
    'tags contains ''allowlist:openclaw_audit_socket_noise''',
    'drop',
    [],
    1
),
(
    3012,
    'Drop SIEM internal syslog reconnect noise',
    'Suppresses expected rsyslog and firewall chatter between the ingest node and OpenClaw during internal syslog reconnect loops.',
    120,
    'tags contains ''allowlist:siem_internal_syslog_reconnect''',
    'drop',
    [],
    1
),
(
    3013,
    'Drop Greenbone expected SSH auth probes',
    'Suppresses expected SSH auth failures and invalid-user probes generated by the vulnerability scanner during scheduled asset checks.',
    130,
    'tags contains ''allowlist:greenbone_expected_ssh_probe''',
    'drop',
    [],
    1
);
