*.* action(
    type="omfwd"
    target="10.20.10.104"
    port="1514"
    protocol="tcp"
    template="RSYSLOG_SyslogProtocol23Format"
    action.resumeRetryCount="-1"
    queue.type="linkedList"
    queue.filename="rdegon-fwd"
    queue.saveOnShutdown="on"
    queue.maxDiskSpace="2g"
    queue.highWatermark="200000"
    queue.lowWatermark="50000"
)
