auth,authpriv.* action(
    type="omfwd"
    target="10.20.10.104"
    port="1514"
    protocol="tcp"
    template="RSYSLOG_SyslogProtocol23Format"
    action.resumeRetryCount="-1"
    queue.type="LinkedList"
    queue.filename="pve-siem-auth"
    queue.maxDiskSpace="512m"
    queue.saveOnShutdown="on"
)

daemon.*,local0.* action(
    type="omfwd"
    target="10.20.10.104"
    port="1518"
    protocol="tcp"
    template="RSYSLOG_SyslogProtocol23Format"
    action.resumeRetryCount="-1"
    queue.type="LinkedList"
    queue.filename="pve-siem-app"
    queue.maxDiskSpace="512m"
    queue.saveOnShutdown="on"
)
