input(
    type="imfile"
    File="/var/log/suricata/eve.json"
    Tag="suricata-eve"
    Facility="local6"
    Severity="info"
    PersistStateInterval="50"
    reopenOnTruncate="on"
    freshStartTail="on"
)

input(
    type="imfile"
    File="/var/log/suricata/fast.log"
    Tag="suricata-fast"
    Facility="local6"
    Severity="warning"
    PersistStateInterval="50"
    reopenOnTruncate="on"
    freshStartTail="on"
)
