ruleset(name="siem_audit_forward") {
    action(
        type="omfwd"
        target="10.20.10.104"
        port="1515"
        protocol="tcp"
        template="RSYSLOG_SyslogProtocol23Format"
        action.resumeRetryCount="-1"
        queue.type="linkedList"
        queue.filename="rdegon-audit-fwd"
    )
}

input(
    type="imfile"
    File="/var/log/audit/audit.log"
    Tag="auditd:"
    Severity="info"
    Facility="local6"
    PersistStateInterval="200"
    Ruleset="siem_audit_forward"
)
