<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Rdegon.WindowsEventAgent.Control</RootNamespace>
    <AssemblyName>Rdegon.WindowsEventAgent.Control</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rdegon.WindowsEventAgent.Common\Rdegon.WindowsEventAgent.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>
</Project>
