from __future__ import annotations

from typing import Any, Callable


def build_default_connector_definitions(
    *,
    schema_version: str,
    now_iso: str,
    normalize_secret_requirements: Callable[[Any], list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    base: list[dict[str, Any]] = [
        {
            "id": "webhook-source",
            "family": "source",
            "block_type": "webhook_source",
            "stage": "ingest",
            "group": "inbound",
            "source_family": "custom_api",
            "title": "Webhook source",
            "description": "Inbound webhook endpoint with auth, schema preview and source binding.",
            "protocols": ["https", "json"],
            "mode": "push",
            "enabled": True,
            "status": "ready",
            "runtime": {
                "direction": "inbound",
                "schedule": "event-driven",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "custom.webhook"},
            "secret_requirements": [{"env": "SIEM_WEBHOOK_SHARED_SECRET", "label": "Webhook shared secret", "required": True}],
        },
        {
            "id": "rest-pull",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "api",
            "source_family": "vendor_api",
            "title": "REST API pull source",
            "description": "Scheduled API pulls from scanners, SaaS products and custom telemetry providers.",
            "protocols": ["https", "oauth2", "token"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "custom.api"},
            "secret_requirements": [{"env": "SIEM_VENDOR_API_TOKEN", "label": "Vendor API token", "required": True}],
        },
        {
            "id": "sql-source",
            "family": "source",
            "block_type": "sql_source",
            "stage": "ingest",
            "group": "database",
            "source_family": "database_sql",
            "title": "SQL database source",
            "description": "Polling SQL connector with query scheduling, checkpoints and replay-friendly offsets.",
            "protocols": ["postgresql", "mysql", "mssql"],
            "mode": "poll",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/10m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "database.events"},
            "secret_requirements": [{"env": "SIEM_DB_POLL_PASSWORD", "label": "DB poll password", "required": True}],
        },
        {
            "id": "nosql-source",
            "family": "source",
            "block_type": "nosql_source",
            "stage": "ingest",
            "group": "database",
            "source_family": "database_nosql",
            "title": "NoSQL database source",
            "description": "Document-store polling for JSON-first telemetry and vendor storage backends.",
            "protocols": ["mongodb", "document-api", "json"],
            "mode": "poll",
            "enabled": False,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/15m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "nosql.events"},
            "secret_requirements": [{"env": "SIEM_VENDOR_API_TOKEN", "label": "NoSQL / vendor token", "required": True}],
        },
        {
            "id": "greenbone-openvas-import",
            "family": "source",
            "block_type": "vuln_runtime",
            "stage": "ingest",
            "group": "vulnerability",
            "source_family": "vulnerability_manager",
            "title": "Greenbone / OpenVAS import",
            "description": "Scheduled import of findings, reports and host exposure from Greenbone-compatible managers.",
            "protocols": ["https", "gmp-api"],
            "mode": "pull",
            "enabled": True,
            "status": "ready",
            "runtime": {
                "direction": "inbound",
                "schedule": "0 */6h",
                "operation": "sync_import",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "vuln_finding", "dataset": "vulnerability.greenbone"},
            "secret_requirements": [{"env": "SIEM_GREENBONE_PASSWORD", "label": "Greenbone password", "required": True}],
        },
        {
            "id": "vuln-manager-rest",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "vulnerability",
            "source_family": "vulnerability_manager",
            "title": "Vulnerability Manager REST import",
            "description": "Generic REST import contract for external vulnerability managers with idempotent scan lifecycle.",
            "protocols": ["https", "oauth2", "token"],
            "mode": "pull",
            "enabled": True,
            "status": "ready",
            "runtime": {
                "direction": "inbound",
                "schedule": "0 */6h",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "vuln_finding", "dataset": "vulnerability.external"},
            "secret_requirements": [{"env": "SIEM_VENDOR_API_TOKEN", "label": "Vulnerability manager token", "required": True}],
        },
        {
            "id": "identity-provider-audit",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "identity",
            "source_family": "identity_provider",
            "title": "Identity provider audit",
            "description": "Audit pulls from Entra, Keycloak or other IdP platforms for sign-in, admin and lifecycle activity.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "identity.audit"},
            "secret_requirements": [{"env": "SIEM_IDP_API_TOKEN", "label": "Identity provider token", "required": True}],
        },
        {
            "id": "endpoint-edr-stream",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "endpoint",
            "source_family": "edr",
            "title": "Endpoint EDR telemetry",
            "description": "High-value endpoint detections and process telemetry from EDR/XDR platforms.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "endpoint.edr"},
            "secret_requirements": [{"env": "SIEM_EDR_API_TOKEN", "label": "EDR API token", "required": True}],
        },
        {
            "id": "cloud-control-plane",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "cloud",
            "source_family": "cloud_audit",
            "title": "Cloud control plane audit",
            "description": "Cloud administration, identity and resource lifecycle events for AWS, Azure or GCP style estates.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/10m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "cloud.audit"},
            "secret_requirements": [{"env": "SIEM_CLOUD_API_TOKEN", "label": "Cloud API token", "required": True}],
        },
        {
            "id": "mail-security-events",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "email",
            "source_family": "mail_security",
            "title": "Mail security and phishing events",
            "description": "Email delivery, phishing, mailbox and collaboration security telemetry.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/10m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "mail.security"},
            "secret_requirements": [{"env": "SIEM_MAILSEC_API_TOKEN", "label": "Mail security token", "required": True}],
        },
        {
            "id": "kubernetes-audit",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "container",
            "source_family": "kubernetes",
            "title": "Kubernetes audit",
            "description": "Cluster control-plane and workload audit trail for container estates.",
            "protocols": ["https", "token", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "kubernetes.audit"},
            "secret_requirements": [{"env": "SIEM_K8S_AUDIT_TOKEN", "label": "Kubernetes audit token", "required": True}],
        },
        {
            "id": "ad-domain-services-audit",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "identity",
            "source_family": "active_directory",
            "title": "Active Directory domain services audit",
            "description": "Security, Kerberos, directory replication and administrative activity from on-prem AD estates.",
            "protocols": ["winrm", "ldap", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "identity.ad"},
            "secret_requirements": [{"env": "SIEM_AD_AUDIT_PASSWORD", "label": "AD audit password", "required": True}],
        },
        {
            "id": "entra-id-audit",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "identity",
            "source_family": "entra_id",
            "title": "Entra ID audit",
            "description": "Cloud sign-in, application consent, identity protection and directory change activity from Entra ID.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "identity.entra"},
            "secret_requirements": [{"env": "SIEM_ENTRA_API_TOKEN", "label": "Entra audit token", "required": True}],
        },
        {
            "id": "proxy-web-gateway",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "network",
            "source_family": "proxy_gateway",
            "title": "Proxy / secure web gateway",
            "description": "HTTP proxy, DNS filtering and web gateway activity with user, asset and egress context.",
            "protocols": ["https", "token", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "network.proxy"},
            "secret_requirements": [{"env": "SIEM_PROXY_API_TOKEN", "label": "Proxy API token", "required": True}],
        },
        {
            "id": "firewall-perimeter-events",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "network",
            "source_family": "firewall",
            "title": "Firewall / NGFW perimeter events",
            "description": "Connection, threat-prevention, VPN and policy decision logs from perimeter firewalls.",
            "protocols": ["https", "syslog", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "network.firewall"},
            "secret_requirements": [{"env": "SIEM_FIREWALL_API_TOKEN", "label": "Firewall API token", "required": True}],
        },
        {
            "id": "saas-audit-events",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "saas",
            "source_family": "saas_audit",
            "title": "SaaS audit events",
            "description": "Productivity, collaboration and business SaaS administrative activity for multi-application estates.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/10m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "saas.audit"},
            "secret_requirements": [{"env": "SIEM_SAAS_AUDIT_TOKEN", "label": "SaaS audit token", "required": True}],
        },
        {
            "id": "cicd-pipeline-audit",
            "family": "source",
            "block_type": "rest_pull",
            "stage": "ingest",
            "group": "devsecops",
            "source_family": "cicd",
            "title": "CI/CD pipeline audit",
            "description": "Build, release, secret usage and pipeline permission events from CI/CD platforms.",
            "protocols": ["https", "oauth2", "json"],
            "mode": "pull",
            "enabled": True,
            "status": "planned",
            "runtime": {
                "direction": "inbound",
                "schedule": "*/5m",
                "supports_dlq": True,
                "supports_replay": True,
                "supports_idempotency": True,
                "supports_backpressure_metrics": True,
                "health": {"last_run_ts": "", "last_status": "never", "success_rate_24h": 0, "consecutive_failures": 0},
            },
            "mappings": {"schema": "normalized_event_v1", "dataset": "cicd.audit"},
            "secret_requirements": [{"env": "SIEM_CICD_API_TOKEN", "label": "CI/CD audit token", "required": True}],
        },
    ]
    connector_overlays: dict[str, dict[str, Any]] = {
        "webhook-source": {
            "telemetry": {
                "collection_depth": "expanded",
                "coverage_score": 78,
                "parsing_coverage_pct": 88.0,
                "telemetry_quality_pct": 86.0,
                "realtime": True,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["generic_events", "alerts", "custom_webhooks"],
                "evidence_fields": ["src_ip", "dst_ip", "user_name", "asset_id", "event_action"],
                "enrichment": ["idempotency", "schema_preview", "source_binding"],
                "investigation_pivots": ["src_ip", "dst_ip", "user_name", "asset_id"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "platform-engineering",
                "playbooks": ["webhook-ticketing", "telegram-primary"],
                "compliance_controls": ["SOC2-CC7", "ISO27001-A.12.4"],
                "runbook_id": "rb-webhook-source",
                "onboarding_template": "tpl-webhook-source",
                "support_tier": "platform",
            },
        },
        "rest-pull": {
            "telemetry": {
                "collection_depth": "expanded",
                "coverage_score": 84,
                "parsing_coverage_pct": 82.0,
                "telemetry_quality_pct": 81.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["api_audit", "configuration", "security_events"],
                "evidence_fields": ["src_ip", "user_name", "asset_id", "event_action", "event_outcome"],
                "enrichment": ["checkpointing", "records_path", "latency_metrics"],
                "investigation_pivots": ["src_ip", "user_name", "asset_id", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "integration-engineering",
                "playbooks": ["webhook-ticketing", "telegram-primary"],
                "compliance_controls": ["NIST-DE.CM", "PCI-DSS-10"],
                "runbook_id": "rb-rest-pull",
                "onboarding_template": "tpl-rest-pull",
                "support_tier": "platform",
            },
        },
        "sql-source": {
            "telemetry": {
                "collection_depth": "basic",
                "coverage_score": 61,
                "parsing_coverage_pct": 62.0,
                "telemetry_quality_pct": 60.0,
                "realtime": False,
                "actor_ip_ready": False,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["database_events", "operational_logs"],
                "evidence_fields": ["asset_id", "user_name", "event_action"],
                "enrichment": ["checkpointing", "query_offsets"],
                "investigation_pivots": ["asset_id", "user_name", "event_action"],
            },
            "operations": {
                "release_stage": "validated",
                "bundle_id": "integrations-foundation-v1",
                "owner": "data-engineering",
                "playbooks": [],
                "compliance_controls": ["ISO27001-A.12.4"],
                "runbook_id": "rb-sql-source",
                "onboarding_template": "tpl-sql-source",
                "support_tier": "community",
            },
        },
        "nosql-source": {
            "telemetry": {
                "collection_depth": "expanded",
                "coverage_score": 80,
                "parsing_coverage_pct": 81.0,
                "telemetry_quality_pct": 80.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["document_events", "api_activity", "operational_logs"],
                "evidence_fields": ["src_ip", "user_name", "asset_id", "event_action"],
                "enrichment": ["checkpointing", "collection_mapping", "tenant_context"],
                "investigation_pivots": ["src_ip", "user_name", "asset_id", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "data-engineering",
                "playbooks": ["ticket-major-incident"],
                "compliance_controls": ["ISO27001-A.12.4", "SOC2-CC7"],
                "runbook_id": "rb-nosql-source",
                "onboarding_template": "tpl-nosql-source",
                "support_tier": "platform",
            },
        },
        "vuln-manager-rest": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 86,
                "parsing_coverage_pct": 85.0,
                "telemetry_quality_pct": 84.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["vulnerability_findings", "scan_runs", "exposure_tracking"],
                "evidence_fields": ["asset_id", "host_name", "dst_ip", "service", "severity", "cves"],
                "enrichment": ["asset_binding", "ticket_mapping", "exposure_timeline"],
                "investigation_pivots": ["asset_id", "host_name", "dst_ip", "service"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "exposure-management",
                "playbooks": ["critical-vulnerability-escalation", "ticket-major-incident"],
                "compliance_controls": ["PCI-DSS-11", "NIST-RA.5"],
                "runbook_id": "rb-vuln-manager-rest",
                "onboarding_template": "tpl-vuln-manager-rest",
                "support_tier": "enterprise",
            },
        },
        "greenbone-openvas-import": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 88,
                "parsing_coverage_pct": 86.0,
                "telemetry_quality_pct": 84.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["vulnerability_findings", "scan_reports"],
                "evidence_fields": ["asset_id", "host_name", "dst_ip", "service", "severity", "cves"],
                "enrichment": ["asset_binding", "incident_policies", "cmdb_linkage"],
                "investigation_pivots": ["asset_id", "dst_ip", "service", "severity"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "exposure-management",
                "playbooks": ["greenbone-fleet-enrollment", "greenbone-import-and-escalate"],
                "compliance_controls": ["CIS-Continuous-Vuln-Management", "PCI-DSS-11"],
                "runbook_id": "rb-greenbone-openvas-import",
                "onboarding_template": "tpl-greenbone-openvas-import",
                "support_tier": "platform",
            },
        },
        "identity-provider-audit": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 84,
                "parsing_coverage_pct": 92.0,
                "telemetry_quality_pct": 89.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["authentication", "admin_actions", "identity_lifecycle"],
                "evidence_fields": ["src_ip", "user_name", "target_user", "event_action", "event_outcome"],
                "enrichment": ["user_baselines", "geo_context", "privileged_actions"],
                "investigation_pivots": ["src_ip", "user_name", "target_user", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "identity-security",
                "playbooks": ["identity-disable"],
                "compliance_controls": ["SOC2-CC6", "ISO27001-A.9"],
                "runbook_id": "rb-identity-provider-audit",
                "onboarding_template": "tpl-identity-provider-audit",
                "support_tier": "enterprise",
            },
        },
        "endpoint-edr-stream": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 91,
                "parsing_coverage_pct": 93.0,
                "telemetry_quality_pct": 90.0,
                "realtime": True,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["process", "network", "malware", "response_actions"],
                "evidence_fields": ["src_ip", "dst_ip", "process_name", "process_executable", "host_name"],
                "enrichment": ["host_lineage", "containment_state", "hash_context"],
                "investigation_pivots": ["src_ip", "dst_ip", "process_name", "host_name"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "endpoint-security",
                "playbooks": ["contain-host"],
                "compliance_controls": ["NIST-DE.CM", "SOC2-CC7"],
                "runbook_id": "rb-endpoint-edr-stream",
                "onboarding_template": "tpl-endpoint-edr-stream",
                "support_tier": "enterprise",
            },
        },
        "cloud-control-plane": {
            "telemetry": {
                "collection_depth": "expanded",
                "coverage_score": 86,
                "parsing_coverage_pct": 84.0,
                "telemetry_quality_pct": 83.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["cloud_admin", "iam", "resource_changes"],
                "evidence_fields": ["src_ip", "user_name", "asset_id", "event_action"],
                "enrichment": ["tenant_context", "resource_tags", "identity_mapping"],
                "investigation_pivots": ["src_ip", "user_name", "asset_id", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "cloud-security",
                "playbooks": ["cloud-admin-containment"],
                "compliance_controls": ["CIS-Cloud", "ISO27001-A.12.4"],
                "runbook_id": "rb-cloud-control-plane",
                "onboarding_template": "tpl-cloud-control-plane",
                "support_tier": "enterprise",
            },
        },
        "mail-security-events": {
            "telemetry": {
                "collection_depth": "expanded",
                "coverage_score": 84,
                "parsing_coverage_pct": 82.0,
                "telemetry_quality_pct": 81.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["phishing", "mailbox_access", "delivery"],
                "evidence_fields": ["src_ip", "user_name", "target_user", "event_action"],
                "enrichment": ["campaigns", "sender_reputation", "attachment_metadata"],
                "investigation_pivots": ["src_ip", "user_name", "target_user", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "mail-security",
                "playbooks": ["mailbox-contain", "telegram-primary"],
                "compliance_controls": ["SOC2-CC7", "ISO27001-A.12.2"],
                "runbook_id": "rb-mail-security-events",
                "onboarding_template": "tpl-mail-security-events",
                "support_tier": "enterprise",
            },
        },
        "kubernetes-audit": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 82,
                "parsing_coverage_pct": 88.0,
                "telemetry_quality_pct": 85.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["cluster_admin", "pod_exec", "rbac_changes"],
                "evidence_fields": ["src_ip", "user_name", "asset_id", "event_action"],
                "enrichment": ["namespace_context", "workload_mapping", "service_account_linkage"],
                "investigation_pivots": ["src_ip", "user_name", "asset_id", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-foundation-v1",
                "owner": "platform-security",
                "playbooks": ["k8s-workload-quarantine"],
                "compliance_controls": ["CIS-Kubernetes", "NIST-DE.CM"],
                "runbook_id": "rb-kubernetes-audit",
                "onboarding_template": "tpl-kubernetes-audit",
                "support_tier": "enterprise",
            },
        },
        "ad-domain-services-audit": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 88,
                "parsing_coverage_pct": 92.0,
                "telemetry_quality_pct": 90.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["authentication", "kerberos", "group_policy", "directory_changes"],
                "evidence_fields": ["src_ip", "user_name", "target_user", "host_name", "event_action", "event_outcome"],
                "enrichment": ["ad_tiering", "user_to_host", "privileged_group_context"],
                "investigation_pivots": ["src_ip", "user_name", "target_user", "host_name"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-enterprise-v2",
                "owner": "identity-security",
                "playbooks": ["iam-disable-account", "chatops-war-room"],
                "compliance_controls": ["SOC2-CC6", "ISO27001-A.9", "NIST-PR.AC"],
                "runbook_id": "rb-ad-domain-services-audit",
                "onboarding_template": "tpl-ad-domain-services-audit",
                "support_tier": "enterprise",
            },
        },
        "entra-id-audit": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 90,
                "parsing_coverage_pct": 94.0,
                "telemetry_quality_pct": 91.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["authentication", "admin_actions", "conditional_access", "identity_protection"],
                "evidence_fields": ["src_ip", "user_name", "target_user", "event_action", "event_outcome"],
                "enrichment": ["geo_context", "risk_user_state", "app_consent_tracking"],
                "investigation_pivots": ["src_ip", "user_name", "target_user", "event_action"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-enterprise-v2",
                "owner": "identity-security",
                "playbooks": ["iam-disable-account", "chatops-war-room"],
                "compliance_controls": ["SOC2-CC6", "ISO27001-A.9", "NIST-DE.CM"],
                "runbook_id": "rb-entra-id-audit",
                "onboarding_template": "tpl-entra-id-audit",
                "support_tier": "enterprise",
            },
        },
        "proxy-web-gateway": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 86,
                "parsing_coverage_pct": 87.0,
                "telemetry_quality_pct": 85.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["web_access", "dns", "download", "web_policy"],
                "evidence_fields": ["src_ip", "user_name", "dst_ip", "domain", "url", "event_action"],
                "enrichment": ["url_category", "reputation", "outbound_destination"],
                "investigation_pivots": ["src_ip", "user_name", "domain", "dst_ip"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-enterprise-v2",
                "owner": "network-security",
                "playbooks": ["firewall-block-ip", "chatops-war-room"],
                "compliance_controls": ["SOC2-CC7", "ISO27001-A.13", "NIST-DE.CM"],
                "runbook_id": "rb-proxy-web-gateway",
                "onboarding_template": "tpl-proxy-web-gateway",
                "support_tier": "enterprise",
            },
        },
        "firewall-perimeter-events": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 89,
                "parsing_coverage_pct": 90.0,
                "telemetry_quality_pct": 88.0,
                "realtime": True,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["network", "threat_prevention", "vpn", "policy_decision"],
                "evidence_fields": ["src_ip", "dst_ip", "dst_port", "policy_name", "event_action", "event_outcome"],
                "enrichment": ["asset_binding", "network_zone", "threat_signature"],
                "investigation_pivots": ["src_ip", "dst_ip", "dst_port", "policy_name"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-enterprise-v2",
                "owner": "network-security",
                "playbooks": ["firewall-block-ip", "ticket-major-incident"],
                "compliance_controls": ["SOC2-CC7", "ISO27001-A.13", "PCI-DSS-10"],
                "runbook_id": "rb-firewall-perimeter-events",
                "onboarding_template": "tpl-firewall-perimeter-events",
                "support_tier": "enterprise",
            },
        },
        "saas-audit-events": {
            "telemetry": {
                "collection_depth": "expanded",
                "coverage_score": 83,
                "parsing_coverage_pct": 84.0,
                "telemetry_quality_pct": 82.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": False,
                "event_families": ["admin_actions", "sharing", "api_usage", "tenant_changes"],
                "evidence_fields": ["src_ip", "user_name", "target_user", "asset_id", "event_action"],
                "enrichment": ["tenant_context", "app_inventory", "identity_mapping"],
                "investigation_pivots": ["src_ip", "user_name", "target_user", "asset_id"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-enterprise-v2",
                "owner": "cloud-security",
                "playbooks": ["ticket-major-incident", "chatops-war-room"],
                "compliance_controls": ["SOC2-CC7", "ISO27001-A.5", "NIST-DE.CM"],
                "runbook_id": "rb-saas-audit-events",
                "onboarding_template": "tpl-saas-audit-events",
                "support_tier": "enterprise",
            },
        },
        "cicd-pipeline-audit": {
            "telemetry": {
                "collection_depth": "deep",
                "coverage_score": 85,
                "parsing_coverage_pct": 86.0,
                "telemetry_quality_pct": 84.0,
                "realtime": False,
                "actor_ip_ready": True,
                "entity_mapping_ready": True,
                "host_telemetry_ready": True,
                "event_families": ["build", "release", "secret_access", "pipeline_admin"],
                "evidence_fields": ["src_ip", "user_name", "asset_id", "event_action", "pipeline_name", "repo"],
                "enrichment": ["repo_to_pipeline", "deployment_target", "secret_scope"],
                "investigation_pivots": ["src_ip", "user_name", "pipeline_name", "repo"],
            },
            "operations": {
                "release_stage": "active",
                "bundle_id": "integrations-enterprise-v2",
                "owner": "devsecops",
                "playbooks": ["cicd-freeze-pipeline", "chatops-war-room"],
                "compliance_controls": ["SOC2-CC8", "ISO27001-A.14", "NIST-PR.IP"],
                "runbook_id": "rb-cicd-pipeline-audit",
                "onboarding_template": "tpl-cicd-pipeline-audit",
                "support_tier": "enterprise",
            },
        },
    }
    rows: list[dict[str, Any]] = []
    for item in base:
        overlay = connector_overlays.get(str(item.get("id") or ""), {})
        telemetry = {
            "collection_depth": "basic",
            "coverage_score": 50,
            "parsing_coverage_pct": 0.0,
            "telemetry_quality_pct": 0.0,
            "realtime": False,
            "actor_ip_ready": False,
            "entity_mapping_ready": False,
            "host_telemetry_ready": False,
            "event_families": [],
            "evidence_fields": [],
            "enrichment": [],
            "investigation_pivots": [],
            **dict(overlay.get("telemetry") or {}),
        }
        operations = {
            "release_stage": "draft",
            "bundle_id": "",
            "owner": "platform-engineering",
            "playbooks": [],
            "compliance_controls": [],
            "runbook_id": "",
            "onboarding_template": "",
            "support_tier": "community",
            **dict(overlay.get("operations") or {}),
        }
        rows.append(
            {
                "type": "connector_definition",
                "schema_version": schema_version,
                "updated_ts": now_iso,
                "labels": [],
                **item,
                "telemetry": telemetry,
                "operations": operations,
                "secret_requirements": normalize_secret_requirements(item.get("secret_requirements")),
            }
        )
    return rows


def build_default_response_actions(
    *,
    schema_version: str,
    now_iso: str,
    normalize_secret_requirements: Callable[[Any], list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    return [
        {
            "id": "telegram-primary",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "telegram",
            "title": "Telegram primary channel",
            "description": "Low-latency human notification for analyst and manager escalation.",
            "enabled": True,
            "dangerous": False,
            "approval_required": False,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {"api_base_url": "https://api.telegram.org", "chat_id_env": "SIEM_TELEGRAM_CHAT_ID"},
            "message_template": "[{severity}] {title}: {message}",
            "owners": ["soc-ops"],
            "trigger_kinds": ["incident", "manual", "alert"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "notification",
            "governance_tier": "operator",
            "evidence_contract": ["incident_ref", "severity", "source_summary", "actors"],
            "rollback_contract": [],
            "rollback_required": False,
            "compliance_controls": ["SOC2-CC7", "ISO27001-A.16"],
            "preconditions": ["telegram-channel-verified", "incident-context-present"],
            "integration_targets": ["telegram"],
            "operator_notes": "Use for analyst-visible notification only; not a state-changing control.",
            "rollback_notes": "Notifications are immutable; follow up with corrective analyst communication if required.",
            "secret_requirements": normalize_secret_requirements(
                [{"env": "SIEM_TELEGRAM_BOT_TOKEN", "label": "Telegram bot token", "required": True}]
            ),
        },
        {
            "id": "webhook-ticketing",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "webhook",
            "title": "Webhook ticketing bridge",
            "description": "Ticketing and case-system handoff for detections promoted into case flow.",
            "enabled": True,
            "dangerous": False,
            "approval_required": False,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {"url_env": "SIEM_WEBHOOK_BRIDGE_URL", "method": "POST"},
            "message_template": "{title}: {message}",
            "owners": ["soc-ops", "service-management"],
            "trigger_kinds": ["incident", "case", "manual"],
            "default_linkage": {"trigger_kind": "case"},
            "playbook_class": "ticketing",
            "governance_tier": "system",
            "evidence_contract": ["title", "message", "severity", "linkage"],
            "rollback_contract": ["ticket_id"],
            "compliance_controls": ["SOC2-CC7", "NIST-RS.AN"],
            "preconditions": ["ticketing-webhook-reachable", "case-linkage-present"],
            "integration_targets": ["ticketing", "case-management"],
            "operator_notes": "Use when the incident is ready for case promotion or managed service handoff.",
            "rollback_notes": "If enrichment is wrong, close or relabel the created ticket and document the correction in the case.",
            "secret_requirements": normalize_secret_requirements(
                [{"env": "SIEM_WEBHOOK_SHARED_SECRET", "label": "Webhook bridge secret", "required": True}]
            ),
        },
        {
            "id": "account-disable-approval",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "approval_gate",
            "title": "Disable account (approval gated)",
            "description": "Template for dangerous actions that must be approved before execution.",
            "enabled": True,
            "dangerous": True,
            "approval_required": True,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {},
            "message_template": "{message}",
            "owners": ["identity-security", "soc-lead"],
            "trigger_kinds": ["incident", "manual"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "containment",
            "governance_tier": "high-risk",
            "evidence_contract": ["case_id", "alert_id", "detection_id", "approval_reason"],
            "rollback_contract": ["identity_id", "account_state"],
            "compliance_controls": ["SOC2-CC6", "ISO27001-A.9", "NIST-PR.AC"],
            "preconditions": ["identity-confirmed", "approval-chain-satisfied", "rollback-path-defined"],
            "integration_targets": ["identity-provider", "access-governance"],
            "operator_notes": "Run only when identity scope and blast radius are confirmed in the linked case.",
            "rollback_notes": "Restore prior account state through the identity provider and document the reversal ticket.",
            "secret_requirements": [],
        },
        {
            "id": "ticket-major-incident",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "webhook",
            "title": "Major incident ticket bridge",
            "description": "Create or update tracked tickets in ITSM systems for major incidents and enterprise escalations.",
            "enabled": True,
            "dangerous": False,
            "approval_required": False,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {"url_env": "SIEM_TICKETING_WEBHOOK_URL", "method": "POST"},
            "message_template": "Create or update major incident {{case_id}} with {{severity}} and analyst summary.",
            "owners": ["soc-ops", "service-management"],
            "trigger_kinds": ["incident", "case", "manual"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "ticketing",
            "governance_tier": "system",
            "evidence_contract": ["case_id", "severity", "incident_summary", "actors"],
            "rollback_contract": ["ticket_id", "priority"],
            "compliance_controls": ["SOC2-CC7", "NIST-RS.CO"],
            "preconditions": ["case-linkage-present", "major-incident-classified"],
            "integration_targets": ["jira", "servicenow", "ticketing"],
            "operator_notes": "Use for managed escalation, change-board visibility and major-incident tracking.",
            "rollback_notes": "Downgrade or resolve the external ticket and document the reason in the linked case.",
            "secret_requirements": normalize_secret_requirements(
                [{"env": "SIEM_WEBHOOK_SHARED_SECRET", "label": "Ticketing bridge secret", "required": True}]
            ),
        },
        {
            "id": "chatops-war-room",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "webhook",
            "title": "ChatOps war-room sync",
            "description": "Provision or update analyst collaboration channels for investigations, escalation and approvals.",
            "enabled": True,
            "dangerous": False,
            "approval_required": False,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {"url_env": "SIEM_CHATOPS_WEBHOOK_URL", "method": "POST"},
            "message_template": "Create war-room for {{case_id}} with {{severity}} and assigned owners.",
            "owners": ["soc-ops", "incident-command"],
            "trigger_kinds": ["incident", "case", "manual"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "communication",
            "governance_tier": "operator",
            "evidence_contract": ["case_id", "severity", "owners", "war_room_topic"],
            "rollback_contract": ["channel_id"],
            "compliance_controls": ["SOC2-CC7", "ISO27001-A.16"],
            "preconditions": ["incident-context-present", "owner-list-present"],
            "integration_targets": ["telegram", "slack", "teams", "chatops"],
            "operator_notes": "Use when the incident needs a persistent collaboration thread and executive visibility.",
            "rollback_notes": "Archive the room after closure and store the closure note with the case.",
            "secret_requirements": normalize_secret_requirements(
                [{"env": "SIEM_CHATOPS_WEBHOOK_TOKEN", "label": "ChatOps webhook token", "required": True}]
            ),
        },
        {
            "id": "firewall-block-ip",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "approval_gate",
            "title": "Block IP on firewall",
            "description": "Push a temporary or permanent block toward firewall and NGFW controls after approval.",
            "enabled": True,
            "dangerous": True,
            "approval_required": True,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {},
            "message_template": "Block {{src_ip}} or {{indicator}} on perimeter controls with rollback timer.",
            "owners": ["network-security", "soc-lead"],
            "trigger_kinds": ["incident", "alert", "manual"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "containment",
            "governance_tier": "high-risk",
            "evidence_contract": ["case_id", "src_ip", "indicator", "approval_reason"],
            "rollback_contract": ["ticket_id", "block_rule_id", "expiry_ts"],
            "compliance_controls": ["SOC2-CC7", "ISO27001-A.13", "NIST-RS.MI"],
            "preconditions": ["block-target-confirmed", "approval-chain-satisfied", "rollback-path-defined"],
            "integration_targets": ["firewall", "ngfw", "ticketing"],
            "operator_notes": "Validate ownership, NAT context and business impact before enforcement.",
            "rollback_notes": "Remove the firewall rule, verify traffic restoration and document validation.",
            "secret_requirements": [],
        },
        {
            "id": "edr-isolate-endpoint",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "approval_gate",
            "title": "Isolate endpoint in EDR",
            "description": "Apply endpoint isolation through EDR/XDR controls with analyst approval and rollback tracking.",
            "enabled": True,
            "dangerous": True,
            "approval_required": True,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {},
            "message_template": "Isolate {{host_name}} / {{asset_id}} in EDR and preserve case context.",
            "owners": ["endpoint-security", "soc-lead"],
            "trigger_kinds": ["incident", "alert", "manual"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "containment",
            "governance_tier": "high-risk",
            "evidence_contract": ["case_id", "asset_id", "host_name", "containment_reason"],
            "rollback_contract": ["asset_id", "edr_session_id", "containment_state"],
            "compliance_controls": ["SOC2-CC7", "NIST-RS.MI", "ISO27001-A.12.6"],
            "preconditions": ["asset-confirmed", "approval-chain-satisfied", "rollback-path-defined"],
            "integration_targets": ["edr", "ticketing", "case-management"],
            "operator_notes": "Use when execution or persistence activity is validated and host isolation is justified.",
            "rollback_notes": "Release isolation after validation, confirm telemetry recovery and update the case.",
            "secret_requirements": [],
        },
        {
            "id": "iam-disable-account",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "approval_gate",
            "title": "Disable account in IAM/IdP",
            "description": "Disable or suspend user access through IAM, IdP or directory integrations.",
            "enabled": True,
            "dangerous": True,
            "approval_required": True,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {},
            "message_template": "Suspend {{entity_name}} across IAM controls and preserve linkage to {{case_id}}.",
            "owners": ["identity-security", "soc-lead"],
            "trigger_kinds": ["incident", "alert", "manual"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "containment",
            "governance_tier": "high-risk",
            "evidence_contract": ["case_id", "user_name", "directory_object_id", "approval_reason"],
            "rollback_contract": ["directory_object_id", "previous_state"],
            "compliance_controls": ["SOC2-CC6", "ISO27001-A.9", "NIST-PR.AC"],
            "preconditions": ["identity-confirmed", "approval-chain-satisfied", "rollback-path-defined"],
            "integration_targets": ["iam", "idp", "ad", "entra_id"],
            "operator_notes": "Use after confirming identity ownership, blast radius and compensating controls.",
            "rollback_notes": "Restore the previous access state and capture the reversal in the change record.",
            "secret_requirements": [],
        },
        {
            "id": "cicd-freeze-pipeline",
            "type": "response_action",
            "schema_version": schema_version,
            "kind": "approval_gate",
            "title": "Freeze CI/CD pipeline",
            "description": "Pause release automation or revoke deployment rights for compromised pipelines and build agents.",
            "enabled": True,
            "dangerous": True,
            "approval_required": True,
            "updated_ts": now_iso,
            "health": {"last_execution_ts": "", "last_status": "never", "total_executions": 0},
            "target": {},
            "message_template": "Freeze {{pipeline_name}} / {{repo}} and route remediation through change control.",
            "owners": ["devsecops", "platform-engineering"],
            "trigger_kinds": ["incident", "manual", "finding"],
            "default_linkage": {"trigger_kind": "incident"},
            "playbook_class": "containment",
            "governance_tier": "change_board",
            "evidence_contract": ["case_id", "pipeline_name", "repo", "approval_reason"],
            "rollback_contract": ["pipeline_name", "freeze_state", "change_ticket"],
            "compliance_controls": ["SOC2-CC8", "ISO27001-A.14", "NIST-PR.IP"],
            "preconditions": ["pipeline-confirmed", "approval-chain-satisfied", "change-record-opened"],
            "integration_targets": ["cicd", "ticketing", "chatops"],
            "operator_notes": "Use when the build or release path is under suspicion and production impact is acceptable.",
            "rollback_notes": "Re-enable the pipeline only after secret rotation, validation and documented approval.",
            "secret_requirements": [],
        },
    ]
